name: Benchmark during the day

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - run: |
          pip install jsonlines requests
          git checkout -b benchmark
          git pull
          git config --global user.email "jkitchin@andrew.cmu.edu"
          git config --global user.name "git-benchmark"
          python gm.py
          git add gm.jsonl
          git commit gm.jsonl -m "add data"
          git push -u origin benchmark