name: Benchmark during the day

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
          pip install jsonlines git+https://github.com/jkitchin/claude-light-python.git
	  git checkout -b benchmark
          python gm.py
          git add gm.jsonl
          git commit gm.jsonl -M "add data"
          git push benchmark origin