name: Claude light hardware

on:
  workflow_dispatch:
  schedule:
    - cron: '59 7 * * *'  # daily at 7:59am

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl "http://claude-light.cheme.cmu.edu:5000/api?R=0.12&G=0.45&B=1" 